// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MigrationCreator;
using NewsApp.Configuration;

namespace MigrationCreator.NewsApp
{
    [DbContext(typeof(NewsDbContext))]
    [Migration("20210129131922_MigrationArticles")]
    partial class MigrationArticles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("NewsApp.Models.Article", b =>
                {
                    b.Property<string>("PublishDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("lead")
                        .HasColumnType("TEXT");

                    b.Property<string>("photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("photogallery_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("thumbnail")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<string>("url")
                        .HasColumnType("TEXT");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("NewsApp.Models.ArticleDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("author")
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("lead")
                        .HasColumnType("TEXT");

                    b.Property<string>("original_url")
                        .HasColumnType("TEXT");

                    b.Property<string>("photo")
                        .HasColumnType("TEXT");

                    b.Property<string>("text")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("ArticlesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
